#!/usr/bin/env bash
# Auto-restart wrapper for iq_server.out — GENERATED by start_heimdall.sh
# SIGPIPE is ignored: iq_server survives abrupt client disconnects.
# Max 5 rapid restarts (< 10s each) before giving up to avoid fork bombs.
trap "" PIPE
trap "exit 0" TERM INT HUP
cd "$(dirname "$0")"
_rapid=0
while true; do
    _t0=$(date +%s)
    chrt -f 99 ./_daq_core/iq_server.out
    rc=$?
    _elapsed=$(( $(date +%s) - _t0 ))
    echo "[iq_server] exited (rc=${rc}) after ${_elapsed}s at $(date '+%H:%M:%S')" \
        >> _logs/iq_server.log
    if [[ $_elapsed -lt 10 ]]; then
        (( _rapid++ ))
        if [[ $_rapid -ge 5 ]]; then
            echo "[iq_server] FATAL: 5 rapid exits in a row — DAQ chain is dead, giving up." \
                >> _logs/iq_server.log
            exit 1
        fi
        sleep 2
    else
        _rapid=0    # reset counter if it ran for >10s (genuine restart)
        sleep 1
    fi
done
